esdata:
    image: ubuntu
    command: true
    volumes:
        - /es/data
        - /log

influxdata:
    image: ubuntu
    command: true
    volumes:
        - /data

rabbitdata:
    image: ubuntu
    command: true
    volumes:
        - /data/log
        - /data/mnesia

rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    expose:
        - "5672"
        - "15672"

    volumes_from:
        - rabbitdata

mongodb:
    image: dockerfile/mongodb
    expose:
        - "27017"

elasticsearch:
    image: dockerfile/elasticsearch
    hostname: elasticsearch
    command: /elasticsearch/bin/elasticsearch -Des.config=/config/elasticsearch.yml
    expose:
        - "9200"
        - "9300"

    volumes:
        - ./config:/config

    volumes_from:
        - esdata

influxdb:
    image: tutum/influxdb
    hostname: influx
    expose:
        - "8083"
        - "8086"

    ports:
        - "8083:8083"
        - "8086:8086"

    volumes_from:
        - influxdata

nginx:
    image: nginx:1.7
    links:
        - web:web
    volumes:
        - ./config/nginx/capuchin.conf:/etc/nginx/conf.d/default.conf
        - .:/app
    ports:
        - "80:80"

web:
    build: .
    command: supervisord -c /config/supervisor.conf -n
    volumes:
        - .:/app
        - ./config:/config
    links:
        - mongodb:mongo
        - elasticsearch:es
        - influxdb:influx
        - rabbitmq:mq
    expose:
        - "8000:8000"
    environment:
        SERVER_NAME: capuchin.dev
