esdata:
    extends:
        file: ./common.yml
        service: esdata

influxdata:
    extends:
        file: ./common.yml
        service: influxdata

rabbitdata:
    extends:
        file: ./common.yml
        service: rabbitdata

rabbitmq:
    extends:
        file: ./common.yml
        service: rabbitmq

    volumes_from:
        - rabbitdata

mongodb:
    extends:
        file: ./common.yml
        service: mongodb

elasticsearch:
    extends:
        file: ./common.yml
        service: elasticsearch

    volumes_from:
        - esdata

influxdb:
    extends:
        file: ./common.yml
        service: influxdb

    volumes_from:
        - influxdata

web:
    extends:
        file: ./common.yml
        service: web
    links:
        - mongodb:mongo
        - elasticsearch:es
        - influxdb:influx
        - rabbitmq:mq
    environment:
        ENVIRONMENT: production
        SERVER_NAME: admin.efprod.com

nginx:
    extends:
        file: ./common.yml
        service: nginx
    links:
        - web
