#cloud-config
output : { all : '| tee -a /var/log/cloud-init-output.log' }

ssh_keys:
    rsa_private: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEA2TkO/HQMhbiyExPftwR79j2KEDJUpNK9/Ub1/C0lQrXa43vm
        YyzYmHMu53l9V4SShgiu0Mb1wdtEJVwOvVeSKmw6GcBwWDvx6rRz+uN22HTFxSzX
        kXYm6sJrZSoaMG7ugB30UNfFcbgWbdzIxjpL5LsUOdVa2nhvtKlSL4BcUYf/5oeF
        p/7ajCMqNYTT8f6E/lgoTgLsllP2q6q2I8PDIyBMT/SC5Rmk7dEW15XV/Kfs4WcI
        63fXGqAEmvZdNifjCS35Qs2UyJ+nPHcHjJriyNcBGaMe2FGK68iGn3H+SRXpib/b
        HK+P0hnlVnUuxhi8h6ZSY5z4dgS7pZCm29+7QwIDAQABAoIBAC8Bn/KVklglnbNv
        K4xJViH1MzlKCvMX/7EdeAG4K0YCYHm1yCdR/xUOZ+oDalJUB/klS982DtyCfH6x
        KydiGelAPlpwQF93qWQm5Ko4KvGwY1PF3mhF7yoCJIdh0wUEHGxxDvunlbyEH6Zq
        jrAG0YGP0lKpjt2UDmhD89r/pfqmUzZlR0a1oH94bU4wAOrZbIl52DADzRCaY5or
        1umpPOlxBoF41i02pRtZOnUj0FFWaePz+wusgGdgRRf51VBI4yG3vp6TVXmydJiA
        qpVNvPmf6i92BUDonmygzxsOt35byxa+2sWrHbCrhga53OgAD/uGrlpa+hWHLqiY
        1BmnwWECgYEA/KXCj8MXEV4JvSkQA+dQEVn713OPx9/L44wsCbSv0HCZ0TInuS05
        iKerKoTz22Rk84oKrwLWuI77IEbeTicpF4Uwo1kJev1p2cL/daP8qDyQHr3MX4iI
        1hqtrTGdYOlwbWdj4gUdliRuV83St5jiYU8OLDvRr1tx6+IqJLJTvwsCgYEA3Br2
        LHHU6zRdSK7IqGwdZ5FT8jt00hqnC+24WFxyTv+IQDmTB+vY/hfAOh28/jhlt9ht
        lwkqYMuIXN504+DaaiMl30afGF4Ap7HDeRtobnlqYEIO6Ma05fciXQYKSeLatZla
        Ui6/8eJbd0EVD2vwtzd2k4auuIq4SD1vTgWp96kCgYAy+5w0eJDqH0jl1Ch4MTB2
        H+tzQc2s7tttErc8SisEbASOM4nSk269xeADl4rCJhM9Fgkr4e3Elo3UqJhpuvtO
        1MDI5cnE+OhoWjJE4g+1P2tx2KkqShoa4o1TmuSATvsyCKAeVxvuVXGy5ET2abKd
        Il/gyz14HoLxr9UDTL0bmwKBgQDWda7HP2Kmii8aUrNQ54b/EqsoqqX40d9R0B5+
        ehUmw/SOH4sTfMnBSoMSHUe4rFrv9wFQ2K1iAu6rDlX2c3BdWkHce4Moyu74dkxw
        BDSM7+CmSbcdN/+q0lG5Mdl0hIV1zCYlTUfY9yUH3XIXxKSW4IO42tIDHabRPIrn
        Cr3BgQKBgQDqv5FrSfMhWwH5eqIaXPlOAGTbWuE15w1woqMGi78u6zz3qFpySYNS
        CVj7ZP0CfbhvwiT7++5sephhPs+73D+kune637SELo36zPCmynIICVhmEliUzKdi
        rU0sqhgZMFuN3coDCn9pw13cufHNBi4ZOhmp49wfaRhM+9Eny8VZTg==
        -----END RSA PRIVATE KEY-----

    rsa_public: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZOQ78dAyFuLITE9+3BHv2PYoQMlSk0r39RvX8LSVCtdrje+ZjLNiYcy7neX1XhJKGCK7QxvXB20QlXA69V5IqbDoZwHBYO/HqtHP643bYdMXFLNeRdibqwmtlKhowbu6AHfRQ18VxuBZt3MjGOkvkuxQ51VraeG+0qVIvgFxRh//mh4Wn/tqMIyo1hNPx/oT+WChOAuyWU/arqrYjw8MjIExP9ILlGaTt0RbXldX8p+zhZwjrd9caoASa9l02J+MJLflCzZTIn6c8dweMmuLI1wEZox7YUYrryIafcf5JFemJv9scr4/SGeVWdS7GGLyHplJjnPh2BLulkKbb37tD chris@entropealabs.com


packages:
    - git
    - python-pip

runcmd:
    - sed -i -e '$a    IdentityFile /etc/ssh/ssh_host_rsa_key' /etc/ssh/ssh_config
    - restart ssh
    - curl -sSL https://get.docker.com/ubuntu/ | sudo sh
    - pip install fig
    - ssh-keyscan github.com >> /root/.ssh/known_hosts
    - git clone git@github.com:edgeflip/capuchin.git /app
    - cd /app
    - fig -f docker-compose.yml up -d
