#cloud-config
output : { all : '| tee -a /var/log/cloud-init-output.log' }

ssh_keys:
    rsa_private: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEogIBAAKCAQEAvgmDxdPdEKST4BuJmNsbP/tEc4CJsDKmWSQFdpAvFRczbYbM
        +pEdTggSB1mw39Kd/cEd92ajs8RFYeh3fQGif7QxE4Kuiqi6aPFkrACczIkSqmop
        aAtk8XXzPdqZgvpg4xkfKOZL7pGAV0BXDpSMmg57h+Hs382x7tkaBiAk0mkjqtJS
        J+1UUHkfv/M3DDvcqjyBav64T+xoC/pNU7KfkgnJy+bm/8QY1V4s6HFTWcvgaesd
        MQhI4l+Vr9SZnmsxr/Zvravd0EAd6vr4iF5Cg9C5uX8zYOxo8JSEJ+Omnxq8qpf8
        zoxbxkKkpVyXmdg0LIpmgQ57yAAVtE57lDytewIDAQABAoIBAHxY93uD9RwFxKkY
        +8EkZcFI5fJ6Ah5kFgswEc8R62zugH1Dfm7ac4VyrHFY0+6w/yZirfwLkkR3wjqd
        hUorvqu3OYGduh4K5+bxRUFzKSaA7tDJpIxrIEMLPf2UQ2y77pfLAWOexcK2PHdb
        J1voAdRwc45nW7rZ+nriXi/x6oYumR8KzLcEZzwAzsW9zgqJzqB2zrZHAVx3c5AE
        K4G/KOhgP8ISUtDaFTzyUlj0BDqDbYuVrEBfeeaaNyvcp5E+o1JnawVtNclurov4
        BOvLzj4nu20dqFkNJeBbLqEOsFoTkj2TRKMZW5nayZi32F+rU7vmyUuExbRQXcdg
        DAJNfDECgYEA+OyGenQH5gfUF3MaXebMrpwwoJauOjU1aiLoFCNaXM8nWr7RlIOg
        CaW1EXUQGnYcwep+l3uq5OiGrq8xXKuY7T9lEZIZb/KYnd+jwzD1+JsDrx/fjWYD
        NQ6/CmDFrKDqytrQg16UTZ5M7sx/Rw5Q2obKmjJbkER61XC05Zb8wokCgYEAw3B1
        GEpTp4f0ErCxfz75RU+y7BZ3eiM8F8GvOu0xeLZmnuocs5NaDhTjkrHHegcm/Cpu
        ebJ0BSiDEJ98viDOEr3PzvdmZq+24+h2TKR0UUa5DqeJ370v2ti5RldWg295r9C8
        vthitNLiAe2nierEABB2BeCwM9GRgBgOyY9HPuMCgYAD8FIsa9uYIzWS7WpUZAuH
        E8edMuUs3JyswkKj1u9eGpUH1Y8hZ3fHz0xvK0gG8yl/VAOOyBErMBa5euIwEjMI
        RgGGZqZqZA9QKDLCKuspdOJ5CesSpLOWSlZxhph6I82zSgUUnxF/rOqQuMGm0S4s
        VwerqvJR9RNwfykNnPcA6QKBgCJdr/lpeHRJD74Jm+yIIkTx0sB44uFzOKnkwO9X
        rg9P45OmDw30py06txmgcTcf8tb8jxiPLJ+LlCBkKwcztYjOH7CBCFyeIUbKJaMs
        d9ei2/+brj7NgZC18z5PNUM/YuJrjgTw/8pUGrHEHGXABl8MhfRaoiE6hJ9Fm7QN
        obWJAoGAO/Qd2R5ubNlS125fYrXIgAroDow5rueN14r2N2WJ4+xmgeis+OUI4XJC
        +r9H7NVOh4WzZMGxmVsbjQoCio5bcsRrwUIadW9iWwY/IKCcjHPLMtee3DaZ7Hi/
        Qcjc2ljdPrrvJWexvXc1rN/snoN0KyIOy0P521XVsv0f7VgrqHc=
        -----END RSA PRIVATE KEY-----

    rsa_public: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+CYPF090QpJPgG4mY2xs/+0RzgImwMqZZJAV2kC8VFzNthsz6kR1OCBIHWbDf0p39wR33ZqOzxEVh6Hd9AaJ/tDETgq6KqLpo8WSsAJzMiRKqailoC2TxdfM92pmC+mDjGR8o5kvukYBXQFcOlIyaDnuH4ezfzbHu2RoGICTSaSOq0lIn7VRQeR+/8zcMO9yqPIFq/rhP7GgL+k1Tsp+SCcnL5ub/xBjVXizocVNZy+Bp6x0xCEjiX5Wv1JmeazGv9m+tq93QQB3q+viIXkKD0Lm5fzNg7GjwlIQn46afGryql/zOjFvGQqSlXJeZ2DQsimaBDnvIABW0TnuUPK17 devs@edgeflip.com


packages:
    - git
    - python-pip
    - nginx

runcmd:
    - sed -i -e '$a    IdentityFile /etc/ssh/ssh_host_rsa_key' /etc/ssh/ssh_config
    - restart ssh
    - curl -sSL https://get.docker.com/ubuntu/ | sudo sh
    - pip install fig
    - ssh-keyscan github.com >> /root/.ssh/known_hosts
    - git clone git@github.com:edgeflip/capuchin.git /app
    - cd /app
    - cp config/nginx/capuchin.conf /etc/nginx/sites-enabled/capuchin
    - rm /etc/nginx/sites-enabled/default
    - service nginx restart
    - fig -f docker-compose.yml up -d
